# Generated by Django 2.0.3 on 2018-03-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildMagicSurgeEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
