# Generated by Django 2.0.3 on 2018-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildmagicsurgeeffect',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
