# Generated by Django 2.0.3 on 2018-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsg', '0002_auto_20180401_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildmagicsurgeeffect',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
